# Generated by Django 4.1.7 on 2023-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColocAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=200)),
                ('status_message', models.CharField(max_length=500)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Coloc',
        ),
    ]
