# Generated by Django 4.2.1 on 2023-06-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coloc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColocAnalysis',
            fields=[
                ('uuid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ColocAnalysisStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_message', models.CharField(max_length=500)),
                ('status_order', models.SmallIntegerField()),
                ('coloc_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coloc_api.colocanalysis')),
            ],
        ),
        migrations.DeleteModel(
            name='Coloc',
        ),
    ]
