# Generated by Django 4.2.1 on 2023-06-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloc_api', '0002_colocanalysis_colocanalysisstatus_delete_coloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colocanalysis',
            name='uuid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
